<?php
/**
 * @file
 * Contains the radar module.
 */

/**
 * Here Implements hook_theme().
 */
function radar_system_theme($existing, $type, $theme, $path)
{
    return array(
        'radarsystem' => array(
            'variables' => array(
                'radar_country' => NULL,
                'radar_city' => NULL,
                'radar_time' => NULL,
            ) ,
            'template' => 'radarsystem'
        ) ,
    );
}